# Site settings
title: Firefly | A Magic Existing
description: "A minimal blog template, build with Jekyll."
url: "cuckoo.daoapp.io"
author:
  name: "Louis Wei"
  email: "yp_liuwei@live.com"
  url: "http://twobitsboy.top"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
